Not using distributed mode
git:
  sha: 8a144f83a287f4d3fece4acdf073f387c5af387d, status: has uncommited changes, branch: main
Namespace(lr=0.0001, lr_backbone=1e-05, batch_size=2, weight_decay=0.0001, epochs=300, lr_drop=200, clip_max_norm=0.1, frozen_weights=None, backbone='resnet50', dilation=False, position_embedding='sine', enc_layers=6, dec_layers=6, dim_feedforward=2048, hidden_dim=256, dropout=0.1, nheads=8, num_queries=100, pre_norm=False, masks=False, aux_loss=True, set_cost_class=1, set_cost_bbox=5, set_cost_giou=2, mask_loss_coef=1, dice_loss_coef=1, bbox_loss_coef=5, giou_loss_coef=2, eos_coef=0.1, dataset_file='historical', data_path='../datset/', coco_panoptic_path=None, remove_difficult=False, output_dir='', device='cuda', seed=42, resume='', start_epoch=0, eval=False, num_workers=2, world_size=1, dist_url='env://', distributed=False)
number of params: 41280266
Traceback (most recent call last):
  File "C:\Users\chris\Desktop\SUS\detr\main.py", line 266, in <module>
    main(args)
  File "C:\Users\chris\Desktop\SUS\detr\main.py", line 150, in main
    dataset_train = build_dataset(image_set='train', args=args)
  File "C:\Users\chris\Desktop\SUS\detr\datasets\__init__.py", line 22, in build_dataset
    return build_historical(image_set, args)
  File "C:\Users\chris\Desktop\SUS\detr\datasets\historical.py", line 149, in build
    assert root.exists(), f'provided historical path {root} does not exist'
AssertionError: provided historical path ..\datset does not exist