2022-03-30 10:35:30,837 INFO    MainThread:11856 [wandb_setup.py:_flush():75] Loading settings from C:\Users\chris\.config\wandb\settings
2022-03-30 10:35:30,838 INFO    MainThread:11856 [wandb_setup.py:_flush():75] Loading settings from C:\Users\chris\Desktop\SUS\detr\wandb\settings
2022-03-30 10:35:30,838 INFO    MainThread:11856 [wandb_setup.py:_flush():75] Loading settings from environment variables: {}
2022-03-30 10:35:30,838 INFO    MainThread:11856 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-03-30 10:35:30,838 INFO    MainThread:11856 [wandb_init.py:_log_setup():405] Logging user logs to C:\Users\chris\Desktop\SUS\detr\wandb\run-20220330_103530-3cy45cy2\logs\debug.log
2022-03-30 10:35:30,839 INFO    MainThread:11856 [wandb_init.py:_log_setup():406] Logging internal logs to C:\Users\chris\Desktop\SUS\detr\wandb\run-20220330_103530-3cy45cy2\logs\debug-internal.log
2022-03-30 10:35:30,840 INFO    MainThread:11856 [wandb_init.py:init():439] calling init triggers
2022-03-30 10:35:30,840 INFO    MainThread:11856 [wandb_init.py:init():442] wandb.init called with sweep_config: {}
config: {}
2022-03-30 10:35:30,841 INFO    MainThread:11856 [wandb_init.py:init():492] starting backend
2022-03-30 10:35:30,841 INFO    MainThread:11856 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=spawn, using: spawn
2022-03-30 10:35:30,849 INFO    MainThread:11856 [backend.py:ensure_launched():219] starting backend process...
2022-03-30 10:35:30,897 ERROR   MainThread:11856 [wandb_init.py:init():981] error
Traceback (most recent call last):
  File "C:\Users\chris\venv\lib\site-packages\wandb\sdk\wandb_init.py", line 954, in init
    run = wi.init()
  File "C:\Users\chris\venv\lib\site-packages\wandb\sdk\wandb_init.py", line 499, in init
    backend.ensure_launched()
  File "C:\Users\chris\venv\lib\site-packages\wandb\sdk\backend\backend.py", line 222, in ensure_launched
    self.wandb_process.start()
  File "C:\Users\chris\AppData\Local\Programs\Python\Python39\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Users\chris\AppData\Local\Programs\Python\Python39\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "C:\Users\chris\AppData\Local\Programs\Python\Python39\lib\multiprocessing\popen_spawn_win32.py", line 45, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\chris\AppData\Local\Programs\Python\Python39\lib\multiprocessing\spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\chris\AppData\Local\Programs\Python\Python39\lib\multiprocessing\spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
